### ISSUE TITLE
Tabulation problems

### ISSUE THREAD

**Issue by includealex** [ivan-egorov42/vim-eo#1]
@ivan-egorov42 there is a plugin problem, that no automatic convertion of '\t' into spaces is implemented. That will lead to execution errors.

**Comment by ivan-egorov42** [comment]
It's not a plugin problem, it's a compiler specific, but you can help yourself by adding `set expandtab` to your `$HOME/.vimrc` configuration file for working with vim. More information in vim by `:help 'expandtab'`

I'll add this to ReadMe.

**Comment by includealex** [comment]
@ivan-egorov42 Well, it really works.
