### ISSUE TITLE
Spaces influence on text inside "".

### ISSUE THREAD

**Issue by includealex** [ivan-egorov42/vim-eo#2]
@ivan-egorov42 When using sprintf, user can easily face such a problem (see images).
[no-space](https://user-images.githubusercontent.com/70340829/184156816-6f9f18ea-d331-436e-ab9c-27a624f9df31.png)
[with-space](https://user-images.githubusercontent.com/70340829/184157024-6aa68170-f090-4270-b7b5-056cdf575190.png)

**Comment by ivan-egorov42** [comment]
Fixed it. Please, close issue
