### ISSUE TITLE
Plugin doesn't highlight `+architect`meta

### ISSUE THREAD

**Issue by mximp** [ivan-egorov42/vim-eo#3]
It seems the plugin doesn't know about the meta:

![image](https://user-images.githubusercontent.com/40247101/185577643-34353b00-c83c-4333-a2fd-eb47b9d67fac.png)

I would expect the plugin highlights the meta in the same way as others.

**Comment by ivan-egorov42** [comment]
@mximp  Fixed it.

**Comment by mximp** [comment]
Thanks!
