### ISSUE TITLE
Incorrect highlighting of bytes literals

### ISSUE THREAD

**Issue by mximp** [ivan-egorov42/vim-eo#4]
Bytes literals are highlighted incorrectly:
![image](https://user-images.githubusercontent.com/40247101/185579885-bd4b1516-9dfc-4913-9baf-cbd9929e57f8.png)

I believe they should be highlighted in the same way as booleans

**Comment by ivan-egorov42** [comment]
@mximp Fixed it.

**Comment by mximp** [comment]
It's better now. Thanks!
