### ISSUE TITLE
why two installation steps?

### ISSUE THREAD

**Issue by yegor256** [ivan-egorov42/vim-eo#7]
README says that I need to do `mkdir -p` first and then `cd` to this dir.

Just one step will be enough. Just `mkdir -p` will ensure that the directory is present.

**Comment by ivan-egorov42** [comment]
@yegor256  tried to shorten this.

**Comment by ivan-egorov42** [comment]
@yegor256 Pls, close issue if this is OK.

**Comment by yegor256** [comment]
@ivan-egorov42 try to get rid of the "if"

**Comment by ivan-egorov42** [comment]
@yegor256 tried to fix it.

**Comment by yegor256** [comment]
@ivan-egorov42 this won't work, if the directory is absent. think a bit more.

**Comment by ivan-egorov42** [comment]
@yegor256 it works for me. 
Also, it's just an example because vim users can have their own directory with plugins. So I shouldn't force them to make a new directory.

**Comment by yegor256** [comment]
@ivan-egorov42 my mistake. works for me.
